name: Deploy

on:
  push:
    branches: [ main ]

jobs:
  deploy-fe:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: cd to front-end
      run: cd front-end

    - name: Install production dependencies
      run: pwd && npm install

    - name: Build Angular
      run: npm run build

    - name: Deploy to server
      run: echo '${{ secrets.SSH_PRIVATE_KEY }}' > pvt-key.txt &&
        chmod 600 pvt-key.txt &&
        rsync -avz --delete --mkpath
        -e "ssh -o StrictHostKeyChecking=no -i pvt-key.txt"
        ./front-end/dist/discussion-board/* ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:~/WebApps/discussion-board/dist &&
        rm pvt-key.txt

