name: Deploy

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install production dependencies
      run: npm install

    - name: Build Angular
      run: ./node_modules/.bin/ng build

    - name: Deploy to server
      run: echo '${{ secrets.SSH_PRIVATE_KEY }}' > pvt-key.txt &&
        chmod 600 pvt-key.txt &&
        rsync -avz --delete --mkpath
        -e "ssh -o StrictHostKeyChecking=no -i pvt-key.txt"
        ./dir ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:~/WebApps/discussion-board/dir &&
        rm pvt-key.txt

